version: "3"
services:
    mssql:
        image: "mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04"
        environment:
            SA_PASSWORD: "abc_1234"
            ACCEPT_EULA: "Y"
        ports: 
            - "1433:1433"
        volumes:
            - sql_data_volume:/var/opt/mssql
    api:
        build: ../
        depends_on: [mssql]
        ports:
            - "8081:80"

volumes: 
    sql_data_volume: